---
- name: Mettre à jour les paquets
  apt:
    update_cache: yes

- name: Installer les dépendances système
  apt:
    name:
      - python3
      - python3-pip
      - python3-venv
      - git
      - nginx
    state: present

- name: Créer le dossier de l’application
  file:
    path: /var/www/flask_app
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'

- name: Copier tout le projet Flask
  copy:
    src: "{{ playbook_dir }}/../app/"
    dest: /var/www/flask_app/
    owner: ubuntu
    group: ubuntu
    mode: '0755'


- name: Créer un environnement virtuel
  command: python3 -m venv /var/www/flask_app/venv
  args:
    creates: /var/www/flask_app/venv/bin/activate

- name: Installer les dépendances Python
  command: /var/www/flask_app/venv/bin/pip install -r /var/www/flask_app/requirements.txt
  args:
    chdir: /var/www/flask_app

- name: Créer le service systemd pour Flask
  template:
    src: flask.service.j2
    dest: /etc/systemd/system/flask.service

- name: Activer et démarrer le service Flask
  systemd:
    name: flask
    enabled: yes
    state: restarted

# --- Nginx Configuration ---

- name: Supprimer le site par défaut
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Déployer la configuration Nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/flask_app

- name: Activer la configuration Nginx
  file:
    src: /etc/nginx/sites-available/flask_app
    dest: /etc/nginx/sites-enabled/flask_app
    state: link

- name: Vérifier la configuration Nginx
  command: nginx -t

- name: Redémarrer Nginx
  systemd:
    name: nginx
    state: restarted
    enabled: yes
